# Generated by Django 5.2.7 on 2025-10-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='symptom_severity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
