# Generated by Django 5.2.7 on 2025-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostpartumMoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('ANXIOUS', 'Anxious'), ('OVERWHELMED', 'Overwhelmed'), ('TIRED', 'Tired'), ('JOYFUL', 'Joyful')], max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
