# Generated by Django 5.2.7 on 2025-10-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('content_type', models.CharField(choices=[('TIP', 'Tip'), ('FAQ', 'Frequently Asked Question'), ('GUIDE', 'Guide')], max_length=10)),
                ('relevant_mode', models.CharField(choices=[('MENSTRUAL', 'Menstrual'), ('TTC', 'Trying to Conceive'), ('PREGNANCY', 'Pregnancy'), ('POSTPARTUM', 'Postpartum'), ('MENOPAUSE', 'Menopause')], max_length=20)),
                ('week_of_pregnancy', models.PositiveSmallIntegerField(blank=True, help_text='Only for pregnancy guides', null=True)),
            ],
        ),
    ]
